

# This file was *autogenerated* from the file sol.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
print((lambda M: (sum(sum(any(all(M[i,j] > m for m in L[_sage_const_0 ]) for L in (M[i,:j],M[i,j+_sage_const_1 :],M[:i,j].T,M[i+_sage_const_1 :,j].T)) for i in range(M.nrows())) for j in range(M.ncols())),max(max(prod((lambda x: (x.index(True)+_sage_const_1  if True in x else len(x) if len(x) else _sage_const_0 ))([M[i,j] <= m for m in L])for L in (M[i,:j][_sage_const_0 ][::-_sage_const_1 ],M[i,j+_sage_const_1 :][_sage_const_0 ],M[:i,j].T[_sage_const_0 ][::-_sage_const_1 ],M[i+_sage_const_1 :,j].T[_sage_const_0 ])) for i in range(M.nrows())) for j in range(M.ncols()))))(matrix([[*map(int, l.strip())] for l in open("in.txt").readlines()])))

